import type { TeamManager } from "../../components/TeamCarousel";

export const managers: TeamManager[] = [
  {
    name: "Аянот Елена",
    phone: "+7 (949) 537-55-65",
    phoneHref: "tel:+79495375565",
    contactUrl: "https://t.me/Lena_Katana",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/ayanot-elena-card.webp",
  },
  {
    name: "Банитюк Юлия",
    phone: "+7 (949) 578-09-33",
    phoneHref: "tel:+79495780933",
    contactUrl: "https://t.me/Lia_banituk",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/banityuk-yulia-card.webp",
  },
  {
    name: "Хаджинова Алина",
    phone: "+7 (949) 400-92-74",
    phoneHref: "tel:+79494009274",
    contactUrl: "https://t.me/alin_ka160",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/khadzhinova-alina-card.webp",
  },
  {
    name: "Бороха Юли",
    phone: "+7 (918) 295-60-93",
    phoneHref: "tel:+79182956093",
    contactUrl: "https://t.me/juliaborokha24",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/borokha-yuli-card.webp",
  },
  {
    name: "Мельник Сергей",
    phone: "+7 (949) 647-72-56",
    phoneHref: "tel:+79496477256",
    contactUrl: "https://t.me/sergeymcv",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/melnik-sergey-card.webp",
  },
  {
    name: "Медведева Елена",
    phone: "+7 (949) 715-80-77",
    phoneHref: "tel:+79497158077",
    contactUrl: "https://t.me/Elen_md",
    contactLabel: "Написать в Telegram",
    contactExternal: true,
    photoUrl: "/managers/medvedeva-elena-card.webp",
  },
  {
    name: "Ольга Кривуца",
    phone: "+7 (978) 059-26-69",
    phoneHref: "tel:+79780592669",
    contactUrl: "mailto:olya_malina22@mail.ru",
    contactLabel: "Написать на e-mail",
    contactExternal: false,
    photoUrl: "/managers/olga-krivutsa-card.webp",
  },
  {
    name: "Тсаренко Виктория",
    phone: "+7 (963) 532-80-09",
    phoneHref: "tel:+79635328009",
    contactUrl: "mailto:tsarenko.viktoria2000@mail.ru",
    contactLabel: "Написать на e-mail",
    contactExternal: false,
    photoUrl: "/managers/tsarenko-viktoria-card.webp",
  },
];
